# Generated by Django 2.1.7 on 2023-04-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20230411_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Жанр'),
        ),
    ]
